version: 2.1
 
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node@4.7
    steps:
      - checkout
      - run: npm install
      - run: npm test
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
